#Relatively immutable settings for physical tagger
#Shared between measurements
#Trigger levels for each channel (V)
trigger_1: 0.01
trigger_2: 0.01
trigger_3: 0.1
#Deadtimes for each channel (ps) (clock doesn't need one)
deadtime_1: 50000
deadtime_2: 50000
#This will downsample the specified channel
eventdivider_3: 10